# Generated by Django 4.2.1 on 2023-05-17 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PublisherName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('main_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.maincategories')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('image', models.ImageField(upload_to='media')),
                ('name_book', models.CharField(max_length=150)),
                ('author_book', models.CharField(max_length=150)),
                ('publisher_name', models.CharField(max_length=150)),
                ('publisher_year', models.IntegerField(default=1990)),
                ('ISBN_code', models.CharField(max_length=150)),
                ('institution_that_added_resource', models.CharField(max_length=150)),
                ('institution_where_the_thesis_was_submitted', models.CharField(max_length=150)),
                ('protection_institution', models.CharField(max_length=150)),
                ('magazine', models.CharField(max_length=150)),
                ('description', models.TextField(default='No description')),
                ('page_number', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city_name_of_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.cityname')),
                ('resource_field_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.resourcefield')),
                ('resource_language_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.resourcelanguage')),
                ('resource_type_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.resourcetype')),
            ],
        ),
    ]
