# Generated by Django 4.2.1 on 2023-05-23 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0003_downloadbooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Kitoblar', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='cityname',
            options={'verbose_name': 'Davlat nomi', 'verbose_name_plural': 'Davlat nomi'},
        ),
        migrations.AlterModelOptions(
            name='downloadbooks',
            options={'verbose_name': 'Yuklab olingan kitoblar', 'verbose_name_plural': 'Yuklab olingan kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='maincategories',
            options={'verbose_name': 'Asosiy Kategoriya', 'verbose_name_plural': 'Asosiy Kategoriya'},
        ),
        migrations.AlterModelOptions(
            name='resourcefield',
            options={'verbose_name': 'Resurs sohasi', 'verbose_name_plural': 'Resurs sohasi'},
        ),
        migrations.AlterModelOptions(
            name='resourcelanguage',
            options={'verbose_name': 'Resurs tili', 'verbose_name_plural': 'Resurs tili'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'verbose_name': 'Resurs turi', 'verbose_name_plural': 'Resurs turi'},
        ),
        migrations.AlterField(
            model_name='downloadbooks',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='downloadbooks',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.books'),
        ),
    ]
