# Generated by Django 4.2.1 on 2023-05-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_books_options_alter_cityname_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
